### ISSUE TITLE
Update not happening

### ISSUE THREAD

**Issue by menagerie198** [qawatake/obsidian-card-view-switcher-plugin#14]
The Community Plugin view states I have version 0.3.7 currently installed, with the latest version being 0.4.0. When I update the plugin, it says it has updated, but the version info stays the same. When I run update check again it says update is available, but …. round and round we go.

**Comment by qawatake** [comment]
@menagerie198 

Try to uninstall this plugin and reinstall it from the community plugin tab.

**Comment by menagerie198** [comment]
Nope, no change

**Comment by menagerie198** [comment]
That did it! Cheers
